# Generated by Django 5.2.4 on 2025-08-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='الملف_الشخصي',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('الوظيفة', models.CharField(choices=[('youtuber', 'يوتيوبر'), ('editor', 'ممنتج'), ('thumbnailer', 'مصمم الثمنيل'), ('reviewer', 'مراجع'), ('publisher', 'مسؤول نشر'), ('manager', 'مدير')], max_length=20, verbose_name='الوظيفة')),
                ('المستخدم', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملفات الشخصية',
            },
        ),
    ]
