# Generated by Django 5.2.4 on 2025-08-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='الملف_الشخصي',
            name='الصورة',
            field=models.ImageField(default='default.jpg', upload_to='profile/', verbose_name='الصورة'),
        ),
    ]
