# Generated by Django 5.2.4 on 2025-08-07 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_الملف_الشخصي_الصورة'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='الملف_الشخصي',
            options={},
        ),
        migrations.RemoveField(
            model_name='الملف_الشخصي',
            name='الصورة',
        ),
        migrations.AlterField(
            model_name='الملف_الشخصي',
            name='المستخدم',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
