# Generated by Django 5.2.4 on 2025-08-10 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtuber', '0004_alter_uploadedvideo_options_alter_uploadedvideo_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorRendered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو على Cloudinary')),
                ('public_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='معرّف Cloudinary')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الممنتج')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendered_versions', to='youtuber.uploadedvideo', verbose_name='فيديو المصدر')),
            ],
            options={
                'verbose_name': 'فيديو ممنتج',
                'verbose_name_plural': 'الفيديوهات الممنتجة',
            },
        ),
    ]
