# Generated by Django 5.2.4 on 2025-08-11 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
        ('youtuber', '0004_alter_uploadedvideo_options_alter_uploadedvideo_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorrendered',
            options={'verbose_name': 'فيديو مُمنتج', 'verbose_name_plural': 'الفيديوهات المُمنتجة'},
        ),
        migrations.RemoveField(
            model_name='editorrendered',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='editorrendered',
            name='source',
        ),
        migrations.AddField(
            model_name='editorrendered',
            name='extras',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='editorrendered',
            name='source_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renders', to='youtuber.uploadedvideo', verbose_name='الفيديو الأصلي (من اليوتيوبر)'),
        ),
        migrations.AddField(
            model_name='editorrendered',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الممنتج'),
        ),
        migrations.AlterField(
            model_name='editorrendered',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف Cloudinary'),
        ),
        migrations.AlterField(
            model_name='editorrendered',
            name='title',
            field=models.CharField(max_length=200, verbose_name='اسم الفيديو المُمنتج'),
        ),
        migrations.AddIndex(
            model_name='editorrendered',
            index=models.Index(fields=['user', '-uploaded_at'], name='editor_edit_user_id_d7d6e3_idx'),
        ),
    ]
