# Generated by Django 5.2.4 on 2025-08-11 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_editorrendered_options_and_more'),
        ('youtuber', '0004_alter_uploadedvideo_options_alter_uploadedvideo_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_progress', to='youtuber.uploadedvideo', verbose_name='الفيديو الأصلي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الممنتج الذي بدأ العمل')),
            ],
            options={
                'verbose_name': 'بدء مونتاج',
                'verbose_name_plural': 'بدء المونتاج',
                'indexes': [models.Index(fields=['-started_at'], name='editor_edit_started_56bdb4_idx')],
                'unique_together': {('source_video',)},
            },
        ),
    ]
