# Generated by Django 5.2.4 on 2025-08-12 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_editorprogress'),
        ('youtuber', '0004_alter_uploadedvideo_options_alter_uploadedvideo_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorrendered',
            options={'ordering': ('-uploaded_at',), 'verbose_name': 'فيديو مُمنتج', 'verbose_name_plural': 'الفيديوهات المُمنتجة'},
        ),
        migrations.AddField(
            model_name='editorrendered',
            name='review_note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة المراجع'),
        ),
        migrations.AddField(
            model_name='editorrendered',
            name='status',
            field=models.CharField(choices=[('pending', 'تحت المراجعة'), ('confirmed', 'مؤكد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=10, verbose_name='حالة المراجعة'),
        ),
        migrations.AddField(
            model_name='editorrendered',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AddIndex(
            model_name='editorrendered',
            index=models.Index(fields=['status', '-uploaded_at'], name='editor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='editorrendered',
            index=models.Index(fields=['source_video', '-uploaded_at'], name='editor_source_idx'),
        ),
    ]
