# Generated by Django 5.2.4 on 2025-08-07 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('النص', models.TextField(verbose_name='نص الرسالة')),
                ('التاريخ', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('تم_الحذف', models.BooleanField(default=False, verbose_name='تم الحذف')),
                ('المرسل', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
                ('رد_على', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.message', verbose_name='رد على')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['التاريخ'],
            },
        ),
    ]
