# Generated by Django 5.2.4 on 2025-08-07 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='التاريخ',
        ),
        migrations.RemoveField(
            model_name='message',
            name='المرسل',
        ),
        migrations.RemoveField(
            model_name='message',
            name='النص',
        ),
        migrations.RemoveField(
            model_name='message',
            name='تم_الحذف',
        ),
        migrations.RemoveField(
            model_name='message',
            name='رد_على',
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='رسالة قديمة', verbose_name='محتوى الرسالة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
