# Generated by Django 5.2.4 on 2025-08-08 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(verbose_name='رابط الفيديو على Cloudinary')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('extras', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'فيديو مرفوع',
                'verbose_name_plural': 'الفيديوهات المرفوعة',
            },
        ),
    ]
