# Generated by Django 5.2.4 on 2025-08-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtuber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='title',
            field=models.CharField(default='فيديو بدون اسم', max_length=200, verbose_name='اسم الفيديو'),
            preserve_default=False,
        ),
    ]
