# Generated by Django 5.2.4 on 2025-08-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtuber', '0002_uploadedvideo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='معرف Cloudinary'),
        ),
    ]
