# Generated by Django 5.2.4 on 2025-08-09 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtuber', '0003_uploadedvideo_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedvideo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'فيديو مرفوع', 'verbose_name_plural': 'الفيديوهات المرفوعة'},
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddIndex(
            model_name='uploadedvideo',
            index=models.Index(fields=['user', '-uploaded_at'], name='youtuber_up_user_id_bad15f_idx'),
        ),
    ]
