# Generated by Django 5.2.4 on 2025-08-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='الفيديو',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('العنوان', models.CharField(max_length=255, verbose_name='عنوان الفيديو')),
                ('وصف', models.TextField(blank=True, verbose_name='وصف الفيديو')),
                ('الفيديو_الخام', models.FileField(upload_to='raw_videos/', verbose_name='الفيديو الخام')),
                ('تاريخ_الرفع', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('المالك', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='صاحب الفيديو')),
            ],
            options={
                'verbose_name': 'فيديو',
                'verbose_name_plural': 'الفيديوهات',
            },
        ),
    ]
