# Generated by Django 5.2.4 on 2025-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='الفيديو',
            name='تاريخ_انتهاء_المونتاج',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء المونتاج'),
        ),
        migrations.AddField(
            model_name='الفيديو',
            name='تاريخ_بدء_المونتاج',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء المونتاج'),
        ),
        migrations.AddField(
            model_name='الفيديو',
            name='حالة_المونتاج',
            field=models.PositiveSmallIntegerField(choices=[(0, 'لم يتم المونتاج'), (1, 'جاري المونتاج'), (2, 'تم المونتاج')], db_index=True, default=0, verbose_name='حالة المونتاج'),
        ),
    ]
